### PR TITLE
Fix typos and use consistent punctuation/capitalization

### LINKED ISSUE #20: Typos in Tutorial.xml
3596: 

> Move the 2 Infantry from Germany to Slovakia Hungary for the attack. Use the Tank to blitz Greater Southern Germany and join the attack in Slovakia Hungary! But wait..<br><br>

Should be "But wait..." (missing final dot if this is intended as an ellipsis "...").

Line 3770: 

> <center><b>Research Technolgy</b></center><br>

Should be "Technology".

There are also some arguable inconsistencies in terms of capitalization ("Sea zone" in one sentence, "sea zone" in others), bullet points that start without capital letters followed by bullet points that start with capital letters. As well as bullet points that end with punctuation, and others that don't, etc.

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #20.

I fixed the issues explicitly identified in #20, as well as a few others I came across while reading through the game notes.  In addition, I tried to use consistent punctuation/capitalization throughout the lists, as mentioned in #20.

While my OCD pushed me to make more changes :smile:, I erred on the side of consistency with the surrounding game notes rather than trying to make everything perfect.

### CODE REVIEW

**Comment by ssoloff** [comment]
@tvleavitt If you have time, would you mind taking a quick look at these changes to ensure they address the concerns you raised in #20 appropriately?  Thanks!

**Comment by ZjelcoP** [comment]
@ssoloff Good Job, thx for cleaning it up!

**Comment by tvleavitt** [comment]
> @tvleavitt If you have time, would you mind taking a quick look at these changes to ensure they address the concerns you raised in #20 appropriately? Thanks!

This looks like a vast improvement, you even fixed stuff I forgot to mention! Thanks. I think this will improve the "first impression" aspect of this tutorial on new users significantly.

**Comment by ssoloff** [comment]
Thanks for the review, @tvleavitt.

@ZjelcoP I think this PR and #22 are ready to merge, pending your approval.

**Review by ron-murhammer — APPROVED** [review]

**Pull request merged**
